/* THE SHADERS: the two small programs the graphics card runs for every
   corner and every pixel of the picture. Browser file (the text is plain
   strings, but only a WebGL page can run it).

   VS / FS     -- the picture. FS is Barnwright's fragment shader BYTE FOR
                  BYTE (3ddesign.html 1534-1685): the warm late-afternoon sun
                  vec3(1.32,1.24,1.06), each siding sheet weathering to its
                  own slightly warm or cool colour, and the lawn-green that
                  shiny surfaces reflect below the horizon. Alan likes this
                  look; tools/check-shaders.mjs fails if one character moves.
   FSTRUE      -- the Yoder site's true-colour fragment shader BYTE FOR BYTE
                  (design.html 1854-2048, Sep 20 2026), used when a company
                  sets look.trueColour. It differs from FS in exactly these
                  ways, every one of them about colour (the rest is the same
                  text, and check-shaders proves it):
                    1. two new inputs, uEnvUp / uEnvDn: what a shiny surface
                       sees above and below the horizon now comes from the
                       scene (engine/scene-data.js TRUE_SCENES) instead of a
                       blue sky and a green lawn typed into the shader --
                       right in a yard, wrong in the white room that ships;
                    2. the per-sheet COLOUR shift is gone (each sheet is still
                       a few percent lighter or darker -- a number, not a
                       colour). Alan on a Bellemont Blue 10x20: "the sliding
                       is not the same blue close to front and the middle
                       back there section that have a different tint";
                    3. the sun is grey, vec3(1.244) -- the same brightness by
                       Rec.709 luminance ("all the colors on this side of
                       building look like there is a slight yellow tint");
                    4. the glint off glass is the sun's colour, grey 1.403;
                    5. the highlight on paint is grey 1.019 (it leaned cool);
                    6. comments explaining each of the above.
                  The glass still mirrors its own blue daylight (uSkyG), on
                  purpose: a grey pane vanishes into its frame.
   VSD / FSD   -- the shadow map: depth only.

   THE ONLY CHANGE TO BARNWRIGHT'S VERTEX SHADERS is the building-step table
   (Watch-it-build and the Framing view). Every corner carries its step id
   (aStage); the table uStg holds, per step, x = HIDDEN (1 = hidden) and y =
   how far to lift it (feet). A lifted corner is moved up BEFORE anything else
   uses it -- the screen position, the world position the lighting and haze
   read (vW) and the shadow-map position (vSh) -- so a lowering wall lights
   and shadows correctly. A hidden corner is sent outside the screen, so its
   whole triangle disappears (from the shadow too, because VSD does the same).
   HIDDEN IS 1 so a table nobody ever set (all zeros) means "everything shown,
   nothing lifted" = Barnwright, and aP + 0.0 is exactly aP, so the finished
   picture is unchanged to the last bit.

   The attribute slots are fixed before linking (ATTRIBS) so both programs
   read the 36-byte corners from the same places: position 0, normal 12,
   uv 24, step 32. */

/* the stage table: the only text added to Barnwright's VS and VSD */
export var STAGE_DECL="attribute float aStage;uniform vec4 uStg[32];";
export var STAGE_HEAD="vec4 s=uStg[int(aStage+0.5)];vec3 p=aP+vec3(0.0,s.y,0.0);";
export var STAGE_TAIL="if(s.x>0.5)gl_Position=vec4(2.0,2.0,2.0,1.0);";

export var ATTRIBS={aP:0,aN:1,aUV:2,aStage:3};
export var STRIDE=36;

/* Barnwright's 23 uniforms (1690) and the Yoder site's two (uEnvUp, uEnvDn). */
export var U_NAMES=["uVP","uLVP","uTex","uShadow","uTint","uSun","uEye","uSpec","uGloss","uGlow","uShadStr","uBump","uUnlit","uAge","uGlassM","uFog","uFogC","uSky","uTurf","uAmbLo","uAmbHi","uBounce","uSkyG","uEnvUp","uEnvDn"];

/* ---------- VS: Barnwright's vertex shader (1528-1533) + the stage table ---------- */
export var VS=[
"attribute vec3 aP;attribute vec3 aN;attribute vec2 aUV;",
STAGE_DECL,
"uniform mat4 uVP;uniform mat4 uLVP;",
"varying vec3 vN;varying vec2 vUV;varying vec4 vSh;varying vec3 vW;",
"void main(){"+STAGE_HEAD+"vN=aN;vUV=aUV;vW=p;vSh=uLVP*vec4(p,1.0);gl_Position=uVP*vec4(p,1.0);"+STAGE_TAIL+"}"
].join("\n");

/* ---------- VSD / FSD: Barnwright's shadow-map shaders (1686-1687) + the stage table ---------- */
export var VSD="attribute vec3 aP;uniform mat4 uLVP;"+STAGE_DECL+"void main(){"+STAGE_HEAD+"gl_Position=uLVP*vec4(p,1.0);"+STAGE_TAIL+"}";
export var FSD="precision mediump float;void main(){gl_FragColor=vec4(1.0);}";

/* ---------- FS: Barnwright's fragment shader, byte for byte (3ddesign.html 1534-1685) ---------- */
export var FS=[
"#extension GL_OES_standard_derivatives : enable",
"#ifdef GL_FRAGMENT_PRECISION_HIGH",
"precision highp float;",
"#else",
"precision mediump float;",
"#endif",
"uniform sampler2D uTex;uniform sampler2D uShadow;",
"uniform vec3 uTint;uniform vec3 uSun;uniform vec3 uEye;",
"uniform float uSpec;uniform float uGloss;uniform float uGlow;uniform float uShadStr;",
"uniform float uBump;uniform float uUnlit;uniform float uAge;uniform float uGlassM;",
"uniform vec2 uFog;uniform vec3 uFogC;uniform vec3 uSky;uniform float uTurf;",
"uniform vec3 uAmbLo;uniform vec3 uAmbHi;uniform vec3 uBounce;uniform vec3 uSkyG;",
"varying vec3 vN;varying vec2 vUV;varying vec4 vSh;varying vec3 vW;",
"float shadowAt(vec2 xy,float z,float bias){",
"  float d=texture2D(uShadow,xy).r;",
"  return (z-bias>d)?0.0:1.0;",
"}",
"void main(){",
"  vec4 smp=texture2D(uTex,vUV);",
"  /* unlit multiply decals: soft contact shadows / ambient occlusion */",
"  if(uUnlit>0.5){gl_FragColor=vec4(smp.rgb*uTint,1.0);return;}",
"  vec3 N=normalize(vN);",
"  /* A LAWN IS NOT A CARPET. Two things were missing and both are here rather",
"     than in the texture, because a texture repeats every three feet and the",
"     repeat is half of what gave it away. First the ground rolls -- done in the",
"     normal, not the mesh, so it stays smooth however close you get. Second it",
"     is patchy at three scales at once: broad drift you read as ground shape,",
"     patches a few feet across, and clumping tight enough to be turf. */",
"  float turfN=0.0;",
"  if(uTurf>0.5){",
"    float gx=0.0390*cos(vW.x*0.068+0.7)*sin(vW.z*0.081-1.2)",
"           +0.0460*cos(vW.x*0.151-2.0)*sin(vW.z*0.133+0.6)",
"           +0.0300*cos(vW.x*0.339+1.9)*sin(vW.z*0.301-0.4);",
"    float gz=0.0465*sin(vW.x*0.068+0.7)*cos(vW.z*0.081-1.2)",
"           +0.0405*sin(vW.x*0.151-2.0)*cos(vW.z*0.133+0.6)",
"           +0.0266*sin(vW.x*0.339+1.9)*cos(vW.z*0.301-0.4);",
"    N=normalize(vec3(N.x-gx,N.y,N.z-gz));",
"    vec2 r1=vec2(vW.x*0.921+vW.z*0.389,-vW.x*0.389+vW.z*0.921);",
"    vec2 r2=vec2(vW.x*0.574-vW.z*0.819, vW.x*0.819+vW.z*0.574);",
"    turfN= 0.50*sin(r1.x*0.074+1.3)*sin(r1.y*0.087-0.7)",
"         + 0.30*sin(r2.x*0.201-2.1)*sin(r2.y*0.177+0.4)",
"         + 0.19*sin(vW.x*0.463+0.9)*sin(vW.z*0.429-1.8)",
"         + 0.12*sin(r2.x*1.07-0.5)*sin(r1.y*0.94+1.6);",
"  }",
"#ifdef GL_OES_standard_derivatives",
"  /* bump mapping from the height packed into the texture's alpha channel;",
"     fades out under minification so it can't alias into moire patterns */",
"  if(uBump>0.001){",
"    float tpp=max(fwidth(vUV.x),fwidth(vUV.y))*512.0;",
"    float batt=clamp(1.8-tpp*0.9,0.0,1.0);",
"    if(batt>0.01){",
"      float hgt=smp.a;",
"      vec3 sx=dFdx(vW),sy=dFdy(vW);",
"      /* normalized so every intermediate stays O(1) — safe in fp16 mediump */",
"      float isc=inversesqrt(max(max(dot(sx,sx),dot(sy,sy)),1e-6));",
"      sx*=isc;sy*=isc;",
"      vec3 r1=cross(sy,N),r2=cross(N,sx);",
"      float det=dot(sx,r1);",
"      vec3 sg=sign(det)*((dFdx(hgt)*isc)*r1+(dFdy(hgt)*isc)*r2);",
"      vec3 nb=abs(det)*N-(uBump*batt)*sg;",
"      if(dot(nb,nb)>1e-4)N=normalize(nb);",
"    }",
"  }",
"#endif",
"  /* No paint on earth reflects 100% or 0%. White siding is about 85% and even",
"     matte black is nearer 5, and pinning both ends is what leaves room for a",
"     rib or a panel edge to separate from the sheet it sits on. */",
"  vec3 alb=(smp.rgb*uTint)*0.88+0.045;",
"  /* low-frequency world-space variation breaks up texture tiling */",
"  alb*=1.0+0.040*sin(vW.x*0.31+vW.y*0.23)*sin(vW.z*0.27-vW.y*0.17);",
"  if(uTurf>0.5){",
"    alb*=1.0+0.355*turfN;                      /* thick and thin */",
"    /* dry drift: the thin places go strawy and the thick places go blue-green,",
"       which is what a Florida yard does by the end of August */",
"    alb*=mix(vec3(1.13,1.02,0.81),vec3(0.90,1.03,0.94),clamp(0.5+0.85*turfN,0.0,1.0));",
"    /* and the mower left stripes -- a yard wide, laid across the lot, faint",
"       enough that you would only miss them if they were gone */",
"    float mow=sin((vW.x*0.883-vW.z*0.470)*2.02);",
"    alb*=1.0+0.030*sign(mow)*sqrt(abs(mow));",
"  }",
"  /* per-panel aging: each sheet of siding weathers its own way (uAge = panel width in ft) */",
"  if(uAge>0.5){",
"    float pid=mod(floor(vW.x/uAge)+floor(vW.z/uAge)*9.0,64.0);",
"    float hsh=fract(sin(pid*7.13+1.7)*137.31);",
"    alb*=0.965+0.07*hsh;",
"    alb*=mix(vec3(1.016,1.0,0.968),vec3(0.986,1.0,1.024),hsh);",
"    /* rain throws dirt up the first foot and a half of any wall. Without it",
"       white siding runs the same value from skid to eave and reads as paper. */",
"    alb*=mix(0.885,1.0,clamp((vW.y-0.85)/1.7,0.0,1.0));",
"  }",
"  float ndl=max(0.0,dot(N,uSun));",
"  vec3 sc=vSh.xyz/vSh.w*0.5+0.5;",
"  float sh=1.0;",
"  if(uShadStr>0.001&&sc.x>0.01&&sc.x<0.99&&sc.y>0.01&&sc.y<0.99&&sc.z<1.0){",
"    float px=1.0/2048.0;float s=0.0;",
"    float bias=0.0016+0.0030*(1.0-max(0.0,dot(normalize(vN),uSun)));",
"    for(int i=0;i<4;i++)for(int j=0;j<4;j++){",
"      vec2 o=(vec2(float(i),float(j))-1.5)*2.30*px;",
"      s+=shadowAt(sc.xy+o,sc.z,bias);}",
"    sh=s/16.0;",
"  }",
"  sh=mix(1.0,sh,uShadStr);",
"  float hemi=0.5+0.5*N.y;",
"  vec3 amb=mix(uAmbLo,uAmbHi,hemi);",
"  amb+=uBounce*max(0.0,-N.y);",
"  vec3 V=normalize(uEye-vW);",
"  vec3 col;",
"  if(uGlassM>0.5){",
"    /* real glass: a dark interior seen face-on, the sky mirrored at a slant",
"       (fresnel), clouds from the map drifting through, and a sun glint that",
"       sweeps across the pane as the camera moves */",
"    vec3 R=reflect(-V,N);",
"    float upR=clamp(R.y*0.65+0.5,0.0,1.0);",
"    /* GLASS KEEPS ITS DAYLIGHT. Painted steel mirrors whatever is actually",
"       behind the building -- on a plain sweep that is a white room, and that is",
"       right. A window is not the same: what makes a pane read as a pane is a",
"       dark interior with a cool cast over it, and when the sweep turned the",
"       glass into flat grey the windows vanished into their own frames. Alan's",
"       own check caught it. So the glass mirrors a sky of its own. */",
"    vec3 skyR=mix(vec3(0.55,0.58,0.56),uSkyG*1.06,upR);",
"    skyR*=0.72+0.55*smp.r;",
"    float fres=pow(1.0-max(0.0,dot(N,V)),5.0);",
"    col=mix(vec3(0.016,0.020,0.022)+smp.g*0.06,skyR,clamp(0.22+1.1*fres,0.0,1.0));",
"    col+=vec3(1.5,1.4,1.15)*pow(max(0.0,dot(R,uSun)),220.0)*(0.25+0.75*sh);",
"  } else {",
"    vec3 sun=vec3(1.32,1.24,1.06)*ndl*sh;",
"    col=alb*(amb+sun);",
"    vec3 H=normalize(V+uSun);",
"    float fr=pow(1.0-max(0.0,dot(N,V)),5.0);",
"    float sp=pow(max(0.0,dot(N,H)),uGloss)*uSpec*(1.0+2.2*fr)*(0.25+0.75*sh);",
"    col+=vec3(1.00,1.02,1.06)*sp;",
"    /* what the surface can actually see: sky above the horizon, lawn below.",
"       Painted metal and glossy paint pick this up as a broad sheen. It is what",
"       stops a black roof reading as a hole cut out of the picture. */",
"    vec3 Rv=reflect(-V,N);",
"    float upR=clamp(Rv.y*0.72+0.30,0.0,1.0);",
"    vec3 sky2=mix(vec3(0.66,0.69,0.72),uSky,0.42);",
"    vec3 envc=mix(vec3(0.19,0.20,0.17),sky2,upR);",
"    col+=envc*uSpec*(0.07+1.75*fr)*(0.40+0.60*sh);",
"  }",
"  col=mix(col,vec3(0.55,0.85,1.05),uGlow*0.35);",
"  vec3 xx=col*0.74;",
"  col=clamp((xx*(2.51*xx+0.03))/(xx*(2.43*xx+0.59)+0.14),vec3(0.0),vec3(1.0));",
"  col=pow(col,vec3(0.4545));",
"  float lum2=dot(col,vec3(0.299,0.587,0.114));",
"  col=mix(vec3(lum2),col,1.10);",
"  float fg=smoothstep(uFog.x,uFog.y,length(vW.xz));",
"  col=mix(col,uFogC,fg);",
"  gl_FragColor=vec4(col,1.0);",
"}"
].join("\n");

/* ---------- FSTRUE: the Yoder site's true-colour fragment shader, byte for byte (design.html 1854-2048) ---------- */
export var FSTRUE=[
"#extension GL_OES_standard_derivatives : enable",
"#ifdef GL_FRAGMENT_PRECISION_HIGH",
"precision highp float;",
"#else",
"precision mediump float;",
"#endif",
"uniform sampler2D uTex;uniform sampler2D uShadow;",
"uniform vec3 uTint;uniform vec3 uSun;uniform vec3 uEye;",
"uniform float uSpec;uniform float uGloss;uniform float uGlow;uniform float uShadStr;",
"uniform float uBump;uniform float uUnlit;uniform float uAge;uniform float uGlassM;",
"uniform vec2 uFog;uniform vec3 uFogC;uniform vec3 uSky;uniform float uTurf;",
"uniform vec3 uAmbLo;uniform vec3 uAmbHi;uniform vec3 uBounce;uniform vec3 uSkyG;",
/* WHAT A SHINY SURFACE CAN SEE: open sky above the horizon, ground below.
   These were two colours typed into the shader -- a blue-ish sky and a
   green-ish lawn -- which is right in a yard and wrong in a white room, and
   the white room is what we ship. They belong in the scene table with
   everything else that says what the world around the building looks like. */
"uniform vec3 uEnvUp;uniform vec3 uEnvDn;",
"varying vec3 vN;varying vec2 vUV;varying vec4 vSh;varying vec3 vW;",
"float shadowAt(vec2 xy,float z,float bias){",
"  float d=texture2D(uShadow,xy).r;",
"  return (z-bias>d)?0.0:1.0;",
"}",
"void main(){",
"  vec4 smp=texture2D(uTex,vUV);",
"  /* unlit multiply decals: soft contact shadows / ambient occlusion */",
"  if(uUnlit>0.5){gl_FragColor=vec4(smp.rgb*uTint,1.0);return;}",
"  vec3 N=normalize(vN);",
"  /* A LAWN IS NOT A CARPET. Two things were missing and both are here rather",
"     than in the texture, because a texture repeats every three feet and the",
"     repeat is half of what gave it away. First the ground rolls -- done in the",
"     normal, not the mesh, so it stays smooth however close you get. Second it",
"     is patchy at three scales at once: broad drift you read as ground shape,",
"     patches a few feet across, and clumping tight enough to be turf. */",
"  float turfN=0.0;",
"  if(uTurf>0.5){",
"    float gx=0.0390*cos(vW.x*0.068+0.7)*sin(vW.z*0.081-1.2)",
"           +0.0460*cos(vW.x*0.151-2.0)*sin(vW.z*0.133+0.6)",
"           +0.0300*cos(vW.x*0.339+1.9)*sin(vW.z*0.301-0.4);",
"    float gz=0.0465*sin(vW.x*0.068+0.7)*cos(vW.z*0.081-1.2)",
"           +0.0405*sin(vW.x*0.151-2.0)*cos(vW.z*0.133+0.6)",
"           +0.0266*sin(vW.x*0.339+1.9)*cos(vW.z*0.301-0.4);",
"    N=normalize(vec3(N.x-gx,N.y,N.z-gz));",
"    vec2 r1=vec2(vW.x*0.921+vW.z*0.389,-vW.x*0.389+vW.z*0.921);",
"    vec2 r2=vec2(vW.x*0.574-vW.z*0.819, vW.x*0.819+vW.z*0.574);",
"    turfN= 0.50*sin(r1.x*0.074+1.3)*sin(r1.y*0.087-0.7)",
"         + 0.30*sin(r2.x*0.201-2.1)*sin(r2.y*0.177+0.4)",
"         + 0.19*sin(vW.x*0.463+0.9)*sin(vW.z*0.429-1.8)",
"         + 0.12*sin(r2.x*1.07-0.5)*sin(r1.y*0.94+1.6);",
"  }",
"#ifdef GL_OES_standard_derivatives",
"  /* bump mapping from the height packed into the texture's alpha channel;",
"     fades out under minification so it can't alias into moire patterns */",
"  if(uBump>0.001){",
"    float tpp=max(fwidth(vUV.x),fwidth(vUV.y))*512.0;",
"    float batt=clamp(1.8-tpp*0.9,0.0,1.0);",
"    if(batt>0.01){",
"      float hgt=smp.a;",
"      vec3 sx=dFdx(vW),sy=dFdy(vW);",
"      /* normalized so every intermediate stays O(1) — safe in fp16 mediump */",
"      float isc=inversesqrt(max(max(dot(sx,sx),dot(sy,sy)),1e-6));",
"      sx*=isc;sy*=isc;",
"      vec3 r1=cross(sy,N),r2=cross(N,sx);",
"      float det=dot(sx,r1);",
"      vec3 sg=sign(det)*((dFdx(hgt)*isc)*r1+(dFdy(hgt)*isc)*r2);",
"      vec3 nb=abs(det)*N-(uBump*batt)*sg;",
"      if(dot(nb,nb)>1e-4)N=normalize(nb);",
"    }",
"  }",
"#endif",
"  /* No paint on earth reflects 100% or 0%. White siding is about 85% and even",
"     matte black is nearer 5, and pinning both ends is what leaves room for a",
"     rib or a panel edge to separate from the sheet it sits on. */",
"  vec3 alb=(smp.rgb*uTint)*0.88+0.045;",
"  /* low-frequency world-space variation breaks up texture tiling */",
"  alb*=1.0+0.040*sin(vW.x*0.31+vW.y*0.23)*sin(vW.z*0.27-vW.y*0.17);",
"  if(uTurf>0.5){",
"    alb*=1.0+0.355*turfN;                      /* thick and thin */",
"    /* dry drift: the thin places go strawy and the thick places go blue-green,",
"       which is what a Florida yard does by the end of August */",
"    alb*=mix(vec3(1.13,1.02,0.81),vec3(0.90,1.03,0.94),clamp(0.5+0.85*turfN,0.0,1.0));",
"    /* and the mower left stripes -- a yard wide, laid across the lot, faint",
"       enough that you would only miss them if they were gone */",
"    float mow=sin((vW.x*0.883-vW.z*0.470)*2.02);",
"    alb*=1.0+0.030*sign(mow)*sqrt(abs(mow));",
"  }",
"  /* per-panel aging: each sheet of siding catches the light its own way",
"     (uAge = panel width in ft) */",
"  if(uAge>0.5){",
"    float pid=mod(floor(vW.x/uAge)+floor(vW.z/uAge)*9.0,64.0);",
"    float hsh=fract(sin(pid*7.13+1.7)*137.31);",
"    /* BRIGHTNESS ONLY. Each sheet is a few percent lighter or darker than the",
"       one beside it, which is true of any wall and keeps it from reading as",
"       flat artwork. Alan's call, Sep 20 2026, when he was shown the three",
"       ways this could go.",
"",
"       WHAT CAME OUT was the line under this one:",
"         alb*=mix(vec3(1.016,1.0,0.968),vec3(0.986,1.0,1.024),hsh);",
"       -- a per-sheet COLOUR shift, warm at one end and cool at the other. It",
"       was there to make each sheet look like it had weathered its own way.",
"",
"       Alan, looking at a Bellemont Blue 10x20: \"the sliding is not the same",
"       blue close to front and the middle back there section that have a",
"       different tint\". Measured across that wall, blue-over-red ran 24, 30,",
"       24, 30, 25 -- a quarter swing in how blue the paint reads, in blocks",
"       four feet wide, one per sheet.",
"",
"       ON A WEATHERED BARN IN A YARD IT WAS RIGHT. On this screen it is not:",
"       the designer draws a NEW building, whose siding came off one coil on",
"       one day, and it is what somebody decides a paint colour from. Five",
"       slightly different blues on one wall, none of them quite the swatch,",
"       is the wrong answer to the only question this page is asked. */",
"    alb*=0.965+0.07*hsh;",
"    /* rain throws dirt up the first foot and a half of any wall. Without it",
"       white siding runs the same value from skid to eave and reads as paper. */",
"    alb*=mix(0.885,1.0,clamp((vW.y-0.85)/1.7,0.0,1.0));",
"  }",
"  float ndl=max(0.0,dot(N,uSun));",
"  vec3 sc=vSh.xyz/vSh.w*0.5+0.5;",
"  float sh=1.0;",
"  if(uShadStr>0.001&&sc.x>0.01&&sc.x<0.99&&sc.y>0.01&&sc.y<0.99&&sc.z<1.0){",
"    float px=1.0/2048.0;float s=0.0;",
"    float bias=0.0016+0.0030*(1.0-max(0.0,dot(normalize(vN),uSun)));",
"    for(int i=0;i<4;i++)for(int j=0;j<4;j++){",
"      vec2 o=(vec2(float(i),float(j))-1.5)*2.30*px;",
"      s+=shadowAt(sc.xy+o,sc.z,bias);}",
"    sh=s/16.0;",
"  }",
"  sh=mix(1.0,sh,uShadStr);",
"  float hemi=0.5+0.5*N.y;",
"  vec3 amb=mix(uAmbLo,uAmbHi,hemi);",
"  amb+=uBounce*max(0.0,-N.y);",
"  vec3 V=normalize(uEye-vW);",
"  vec3 col;",
"  if(uGlassM>0.5){",
"    /* real glass: a dark interior seen face-on, the sky mirrored at a slant",
"       (fresnel), clouds from the map drifting through, and a sun glint that",
"       sweeps across the pane as the camera moves */",
"    vec3 R=reflect(-V,N);",
"    float upR=clamp(R.y*0.65+0.5,0.0,1.0);",
"    /* GLASS KEEPS ITS DAYLIGHT. Painted steel mirrors whatever is actually",
"       behind the building -- on a plain sweep that is a white room, and that is",
"       right. A window is not the same: what makes a pane read as a pane is a",
"       dark interior with a cool cast over it, and when the sweep turned the",
"       glass into flat grey the windows vanished into their own frames. Alan's",
"       own check caught it. So the glass mirrors a sky of its own. */",
"    vec3 skyR=mix(vec3(0.55,0.58,0.56),uSkyG*1.06,upR);",
"    skyR*=0.72+0.55*smp.r;",
"    float fres=pow(1.0-max(0.0,dot(N,V)),5.0);",
"    col=mix(vec3(0.016,0.020,0.022)+smp.g*0.06,skyR,clamp(0.22+1.1*fres,0.0,1.0));",
"    /* the glint IS the sun, so it is the sun's colour -- 1.403 by the same",
"       luminance rule that made the sun 1.244 */",
"    col+=vec3(1.403,1.403,1.403)*pow(max(0.0,dot(R,uSun)),220.0)*(0.25+0.75*sh);",
"  } else {",
"    /* THE SUN IS WHITE (Alan, Sep 20 2026: \"all the colors on this side of",
"       building look like there is a slight yellow tint\"). It was",
"       vec3(1.32,1.24,1.06) -- a late-afternoon gold with 25% more red in it",
"       than blue -- and it lands hardest on whichever wall is pointed at it,",
"       so the sunlit end of a blue barn went pale and yellow while the wall",
"       beside it, lit mostly by ambient, stayed blue. Measured off his own",
"       screen: the long wall held 21% more blue than red, the sunlit end only",
"       6%. Two thirds of the colour, gone, on the face he was looking at.",
"       1.244 is the same brightness by Rec.709 luminance, so nothing got",
"       darker -- only honest. A colour picker whose job is telling somebody",
"       what Bellemont Blue looks like cannot light it with a gold lamp. */",
"    vec3 sun=vec3(1.244,1.244,1.244)*ndl*sh;",
"    col=alb*(amb+sun);",
"    vec3 H=normalize(V+uSun);",
"    float fr=pow(1.0-max(0.0,dot(N,V)),5.0);",
"    float sp=pow(max(0.0,dot(N,H)),uGloss)*uSpec*(1.0+2.2*fr)*(0.25+0.75*sh);",
"    /* and the highlight on paint. This one leaned COOL rather than warm",
"       (1.00,1.02,1.06) -- a smaller lie in the other direction, and still a",
"       lie about what colour the light is. */",
"    col+=vec3(1.019,1.019,1.019)*sp;",
"    /* what the surface can actually see: sky above the horizon, lawn below.",
"       Painted metal and glossy paint pick this up as a broad sheen. It is what",
"       stops a black roof reading as a hole cut out of the picture. */",
"    vec3 Rv=reflect(-V,N);",
"    float upR=clamp(Rv.y*0.72+0.30,0.0,1.0);",
"    vec3 sky2=mix(uEnvUp,uSky,0.42);",
"    vec3 envc=mix(uEnvDn,sky2,upR);",
"    col+=envc*uSpec*(0.07+1.75*fr)*(0.40+0.60*sh);",
"  }",
"  col=mix(col,vec3(0.55,0.85,1.05),uGlow*0.35);",
"  vec3 xx=col*0.74;",
"  col=clamp((xx*(2.51*xx+0.03))/(xx*(2.43*xx+0.59)+0.14),vec3(0.0),vec3(1.0));",
"  col=pow(col,vec3(0.4545));",
"  float lum2=dot(col,vec3(0.299,0.587,0.114));",
"  col=mix(vec3(lum2),col,1.10);",
"  float fg=smoothstep(uFog.x,uFog.y,length(vW.xz));",
"  col=mix(col,uFogC,fg);",
"  gl_FragColor=vec4(col,1.0);",
"}"
].join("\n");
